# kubectl create secret generic my-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_Host: c3FsMDE=          # echo -n 'sql01' | base64
  DB_User: cm9vdA==          # echo -n 'root' | base64
  DB_Password: cGFzc3dvcmQxMjM=  # echo -n 'password123' | base64 